name: CI

on:
  pull_request:

jobs:
  files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.changed_files.outputs.only_changed == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v45.0.6
        with:
          files: |
            assets/**
            public/**
            .vscode/**
            .github/**
            !.github/workflows/ci.yml
            **.md
            nodeÀçmodules/** # the committed node modules folder

  typecheck:
    needs: files
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Typecheck

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version to 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Typecheck
        run: npm run typecheck

  test:
    needs: files
    if: needs.files.outputs.should_skip != 'true'

    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    name: Build & Test

    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [18, 20, 22]
        include:
          - os: windows-latest
            node_version: 22
          - os: macos-latest
            node_version: 22
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js version to ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
